#! /bin/bash -e

dir="$(dirname $BASH_SOURCE)"

grph-feed() {
    declare -A data=()
    while read prefix id suffix; do
        data[prefixes]+="$prefix\n"
        data[suffixes]+="$suffix\n"
        data[$suffix->]+="$id "
        data[->$prefix]+="$id "
    done

    suffixes=($(printf "${data[suffixes]}" | sort -u))
    for suffix in ${suffixes[@]}; do
        grph-map "${data[$suffix->]}" "${data[->$suffix]}"
    done
}

grph-map() {
    local from=($1) \
          to=($2)

    [[ -z "$to" ]] && return
    
    for f in ${from[@]}; do
        for t in ${to[@]}; do
            [[ ! $f == $t ]] && echo $f $t
        done
    done
}

grph() {
    "$dir"/lib/fasta.awk "$1" | "$dir"/lib/grph.awk -v k=${2:-3} | grph-feed
}
